import path = require('path')
import * as vscode from 'vscode'
import { LinePath } from '../bookmark-provider/data/model/LinePath'

export class BookmarkIcon {
	showBookmarkOnGutter(editor: vscode.TextEditor, set: Array<LinePath>) {
		const decorationSigle: vscode.DecorationOptions[] = []
		const decorationMulti: vscode.DecorationOptions[] = []
		for (const line of set) {
			if(editor.document.lineCount <= line.line) continue
			const content = editor.document.lineAt(line.line)
			const range = new vscode.Range(content.range.start, content.range.end)
			if (line.ids.length > 1) {
				decorationMulti.push({ range: range })
			} else {
				decorationSigle.push({ range: range })
			}
		}
		editor.setDecorations(this._bookmarkSigle, decorationSigle)
		editor.setDecorations(this._bookmarkMulti, decorationMulti)
	}

	getIcon(icon: IconType, mode?: 'green' | 'dark' | 'light'): vscode.Uri {
		mode = mode ?? (vscode.window.activeColorTheme.kind === vscode.ColorThemeKind.Dark ? 'dark' : 'light')
		return vscode.Uri.file(path.join(__dirname, '..', '..', 'resources', mode, `${icon}.svg`))
	}

	private _getIconGutter(multible: boolean) {
		return vscode.window.createTextEditorDecorationType({
			gutterIconPath: this.getIcon(multible ? IconType.bookmarks_gutter : IconType.bookmark_gutter),
			overviewRulerLane: vscode.OverviewRulerLane.Left,
			overviewRulerColor: 'rgba(0,255,0, 0.7)', // Màu đỏ với độ mờ 70%
			border: 'none', // Không có border để tránh làm nổi bật dòng
		})
	}

	// cần sử dụng biến static để lưu giữ các icon nếu không sẽ không thể thay đổi được
	private _bookmarkMulti = this._getIconGutter(true)
	private _bookmarkSigle = this._getIconGutter(false)
}

export enum IconType {
	bookmark_gutter = 'bookmark_gutter',
	bookmarks_gutter = 'bookmarks_gutter',
	bookmark = 'bookmark',
	bookmarks = 'bookmarks',
	watcher = 'watcher',
	open_folder = 'open_folder',
	folder = 'folder'
}
export const bookmarkIcon = new BookmarkIcon()

// Dark : F6F6F6
// Light : 2d2d30

/*
{lable:'account'}
{lable:'activate-breakpoints'}
{lable:'add'}
{lable:'alert'}
{lable:'archive'}
{lable:'array'}
{lable:'arrow-both'}
{lable:'arrow-circle-down'}
{lable:'arrow-circle-left'}
{lable:'arrow-circle-right'}
{lable:'arrow-circle-up'}
{lable:'arrow-down'}
{lable:'arrow-left'}
{lable:'arrow-right'}
{lable:'arrow-small-down'}
{lable:'arrow-small-left'}
{lable:'arrow-small-right'}
{lable:'arrow-small-up'}
{lable:'arrow-swap'}
{lable:'arrow-up'}
{lable:'azure-devops'}
{lable:'azure'}
{lable:'beaker-stop'}
{lable:'beaker'}
{lable:'bell'}
{lable:'bell-dot'}
{lable:'bell-slash'}
{lable:'bell-slash-dot'}
{lable:'bold'}
{lable:'book'}
{lable:'bookmark'}
{lable:'bracket-dot'}
{lable:'bracket-error'}
{lable:'bracket'}
{lable:'briefcase'}
{lable:'broadcast'}
{lable:'browser'}
{lable:'bug'}
{lable:'calendar'}
{lable:'call-incoming'}
{lable:'call-outgoing'}
{lable:'case-sensitive'}
{lable:'check'}
{lable:'check-all'}
{lable:'checklist'}
{lable:'chevron-down'}
{lable:'chevron-left'}
{lable:'chevron-right'}
{lable:'chevron-up'}
{lable:'chip'}
{lable:'chrome-close'}
{lable:'chrome-maximize'}
{lable:'chrome-minimize'}
{lable:'chrome-restore'}
{lable:'circle-filled'}
{lable:'circle-large-filled'}
{lable:'circle-large-outline'}
{lable:'circle-outline'}
{lable:'circle-slash'}
{lable:'circuit-board'}
{lable:'clear-all'}
{lable:'clippy'}
{lable:'clock'}
{lable:'clone'}
{lable:'close'}
{lable:'close-all'}
{lable:'close-dirty'}
{lable:'cloud'}
{lable:'cloud-download'}
{lable:'cloud-upload'}
{lable:'code'}
{lable:'coffee'}
{lable:'collapse-all'}
{lable:'color-mode'}
{lable:'combine'}
{lable:'comment'}
{lable:'comment-add'}
{lable:'comment-discussion'}
{lable:'comment-draft'}
{lable:'comment-unresolved'}
{lable:'compare-changes'}
{lable:'compass-active'}
{lable:'compass-dot'}
{lable:'compass'}
{lable:'console'}
{lable:'copilot'}
{lable:'credit-card'}
{lable:'dash'}
{lable:'dashboard'}
{lable:'database'}
{lable:'debug-all'}
{lable:'debug'}
{lable:'debug-alt'}
{lable:'debug-alt-small'}
{lable:'debug-breakpoint'}
{lable:'debug-breakpoint-conditional'}
{lable:'debug-breakpoint-conditional-disabled'}
{lable:'debug-breakpoint-conditional-unverified'}
{lable:'debug-breakpoint-data'}
{lable:'debug-breakpoint-data-disabled'}
{lable:'debug-breakpoint-data-unverified'}
{lable:'debug-breakpoint-disabled'}
{lable:'debug-breakpoint-function'}
{lable:'debug-breakpoint-function-disabled'}
{lable:'debug-breakpoint-function-unverified'}
{lable:'debug-breakpoint-log'}
{lable:'debug-breakpoint-log-disabled'}
{lable:'debug-breakpoint-log-unverified'}
{lable:'debug-breakpoint-unsupported'}
{lable:'debug-breakpoint-unverified'}
{lable:'debug-console'}
{lable:'debug-continue-small'}
{lable:'debug-continue'}
{lable:'debug-coverage'}
{lable:'debug-disconnect'}
{lable:'debug-hint'}
{lable:'debug-line-by-line'}
{lable:'debug-pause'}
{lable:'debug-rerun'}
{lable:'debug-restart'}
{lable:'debug-restart-frame'}
{lable:'debug-reverse-continue'}
{lable:'debug-stackframe'}
{lable:'debug-stackframe-active'}
{lable:'debug-stackframe-dot'}
{lable:'debug-stackframe-focused'}
{lable:'debug-start'}
{lable:'debug-step-back'}
{lable:'debug-step-into'}
{lable:'debug-step-out'}
{lable:'debug-step-over'}
{lable:'debug-stop'}
{lable:'desktop-download'}
{lable:'device-camera'}
{lable:'device-camera-video'}
{lable:'device-desktop'}
{lable:'device-mobile'}
{lable:'diff'}
{lable:'diff-added'}
{lable:'diff-ignored'}
{lable:'diff-modified'}
{lable:'diff-removed'}
{lable:'diff-renamed'}
{lable:'discard'}
{lable:'edit'}
{lable:'editor-layout'}
{lable:'ellipsis'}
{lable:'empty-window'}
{lable:'error-small'}
{lable:'error'}
{lable:'exclude'}
{lable:'expand-all'}
{lable:'export'}
{lable:'extensions'}
{lable:'eye'}
{lable:'eye-closed'}
{lable:'eye-unwatch'}
{lable:'eye-watch'}
{lable:'feedback'}
{lable:'file'}
{lable:'file-add'}
{lable:'file-binary'}
{lable:'file-code'}
{lable:'file-directory'}
{lable:'file-directory-create'}
{lable:'file-media'}
{lable:'file-pdf'}
{lable:'file-submodule'}
{lable:'file-symlink-directory'}
{lable:'file-symlink-file'}
{lable:'file-text'}
{lable:'file-zip'}
{lable:'files'}
{lable:'filter-filled'}
{lable:'filter'}
{lable:'flame'}
{lable:'fold'}
{lable:'fold-down'}
{lable:'fold-up'}
{lable:'folder'}
{lable:'folder-active'}
{lable:'folder-library'}
{lable:'folder-opened'}
{lable:'game'}
{lable:'gather'}
{lable:'gear'}
{lable:'gift'}
{lable:'gist'}
{lable:'gist-force'}
{lable:'gist-new'}
{lable:'gist-private'}
{lable:'gist-secret'}
{lable:'git-branch'}
{lable:'git-branch-create'}
{lable:'git-branch-delete'}
{lable:'git-commit'}
{lable:'git-compare'}
{lable:'git-fetch'}
{lable:'git-force-private'}
{lable:'git-merge'}
{lable:'git-pull-request'}
{lable:'git-pull-request-abandoned'}
{lable:'git-pull-request-closed'}
{lable:'git-pull-request-create'}
{lable:'git-pull-request-draft'}
{lable:'git-pull-request-new-changes'}
{lable:'git-pull-request-go-to-changes'}
{lable:'github'}
{lable:'github-action'}
{lable:'github-alt'}
{lable:'github-inverted'}
{lable:'globe'}
{lable:'go-to-file'}
{lable:'grabber'}
{lable:'graph'}
{lable:'graph-left'}
{lable:'graph-line'}
{lable:'graph-scatter'}
{lable:'gripper'}
{lable:'group-by-ref-type'}
{lable:'heart'}
{lable:'history'}
{lable:'home'}
{lable:'horizontal-rule'}
{lable:'hubot'}
{lable:'inbox'}
{lable:'indent'}
{lable:'info'}
{lable:'insert'}
{lable:'inspect'}
{lable:'issue-closed'}
{lable:'issue-draft'}
{lable:'issue-opened'}
{lable:'issue-reopened'}
{lable:'issues'}
{lable:'italic'}
{lable:'jersey'}
{lable:'json'}
{lable:'kebab-horizontal'}
{lable:'kebab-vertical'}
{lable:'key'}
{lable:'keyboard'}
{lable:'law'}
{lable:'layers-active'}
{lable:'layers-dot'}
{lable:'layers'}
{lable:'layout-activitybar-left'}
{lable:'layout-activitybar-right'}
{lable:'layout-centered'}
{lable:'layout-menubar'}
{lable:'layout-panel-center'}
{lable:'layout-panel-justify'}
{lable:'layout-panel-left'}
{lable:'layout-panel-right'}
{lable:'layout-panel'}
{lable:'layout-sidebar-left'}
{lable:'layout-sidebar-right'}
{lable:'layout-statusbar'}
{lable:'layout'}
{lable:'library'}
{lable:'light-bulb'}
{lable:'lightbulb'}
{lable:'lightbulb-autofix'}
{lable:'link'}
{lable:'link-external'}
{lable:'list-filter'}
{lable:'list-flat'}
{lable:'list-ordered'}
{lable:'list-selection'}
{lable:'list-tree'}
{lable:'list-unordered'}
{lable:'live-share'}
{lable:'loading'}
{lable:'location'}
{lable:'lock-small'}
{lable:'lock'}
{lable:'log-in'}
{lable:'log-out'}
{lable:'logo-github'}
{lable:'magnet'}
{lable:'mail'}
{lable:'mail-read'}
{lable:'mail-reply'}
{lable:'mark-github'}
{lable:'markdown'}
{lable:'megaphone'}
{lable:'mention'}
{lable:'menu'}
{lable:'merge'}
{lable:'mic'}
{lable:'mic-filled'}
{lable:'microscope'}
{lable:'milestone'}
{lable:'mirror'}
{lable:'mirror-private'}
{lable:'mirror-public'}
{lable:'more'}
{lable:'mortar-board'}
{lable:'move'}
{lable:'multiple-windows'}
{lable:'music'}
{lable:'mute'}
{lable:'new-file'}
{lable:'new-folder'}
{lable:'newline'}
{lable:'no-newline'}
{lable:'note'}
{lable:'notebook'}
{lable:'notebook-template'}
{lable:'octoface'}
{lable:'open-preview'}
{lable:'organization'}
{lable:'organization-filled'}
{lable:'organization-outline'}
{lable:'output'}
{lable:'package'}
{lable:'paintcan'}
{lable:'pass'}
{lable:'pass-filled'}
{lable:'pencil'}
{lable:'person'}
{lable:'person-add'}
{lable:'person-filled'}
{lable:'person-follow'}
{lable:'person-outline'}
{lable:'pie-chart'}
{lable:'piano'}
{lable:'pin'}
{lable:'pinned'}
{lable:'pinned-dirty'}
{lable:'play'}
{lable:'play-circle'}
{lable:'plug'}
{lable:'plus'}
{lable:'preserve-case'}
{lable:'preview'}
{lable:'primitive-dot'}
{lable:'primitive-square'}
{lable:'project'}
{lable:'pulse'}
{lable:'question'}
{lable:'quote'}
{lable:'radio-tower'}
{lable:'reactions'}
{lable:'record'}
{lable:'record-keys'}
{lable:'record-small'}
{lable:'redo'}
{lable:'references'}
{lable:'refresh'}
{lable:'regex'}
{lable:'remote'}
{lable:'remote-explorer'}
{lable:'remove'}
{lable:'remove-close'}
{lable:'repl'}
{lable:'replace'}
{lable:'replace-all'}
{lable:'reply'}
{lable:'repo'}
{lable:'repo-clone'}
{lable:'repo-create'}
{lable:'repo-delete'}
{lable:'repo-force-push'}
{lable:'repo-forceed'}
{lable:'repo-pull'}
{lable:'repo-push'}
{lable:'repo-sync'}
{lable:'report'}
{lable:'request-changes'}
{lable:'rocket'}
{lable:'root-folder'}
{lable:'root-folder-opened'}
{lable:'rss'}
{lable:'ruby'}
{lable:'run'}
{lable:'run-all'}
{lable:'run-above'}
{lable:'run-below'}
{lable:'run-errors'}
{lable:'save'}
{lable:'save-all'}
{lable:'save-as'}
{lable:'screen-full'}
{lable:'screen-normal'}
{lable:'search'}
{lable:'search-save'}
{lable:'search-stop'}
{lable:'search-fuzzy'}
{lable:'selection'}
{lable:'send'}
{lable:'server'}
{lable:'server-environment'}
{lable:'server-process'}
{lable:'settings'}
{lable:'settings-gear'}
{lable:'shield'}
{lable:'sign-in'}
{lable:'sign-out'}
{lable:'smiley'}
{lable:'snake'}
{lable:'sparkle'}
{lable:'sort-precedence'}
{lable:'source-control'}
{lable:'split-horizontal'}
{lable:'split-vertical'}
{lable:'squirrel'}
{lable:'star'}
{lable:'star-add'}
{lable:'star-delete'}
{lable:'star-empty'}
{lable:'star-full'}
{lable:'star-half'}
{lable:'stop'}
{lable:'stop-circle'}
{lable:'symbol-array'}
{lable:'symbol-boolean'}
{lable:'symbol-class'}
{lable:'symbol-color'}
{lable:'symbol-constant'}
{lable:'symbol-constructor'}
{lable:'symbol-enum'}
{lable:'symbol-enum-member'}
{lable:'symbol-event'}
{lable:'symbol-field'}
{lable:'symbol-file'}
{lable:'symbol-folder'}
{lable:'symbol-function'}
{lable:'symbol-interface'}
{lable:'symbol-key'}
{lable:'symbol-keyword'}
{lable:'symbol-method'}
{lable:'symbol-misc'}
{lable:'symbol-module'}
{lable:'symbol-namespace'}
{lable:'symbol-null'}
{lable:'symbol-number'}
{lable:'symbol-numeric'}
{lable:'symbol-object'}
{lable:'symbol-operator'}
{lable:'symbol-package'}
{lable:'symbol-parameter'}
{lable:'symbol-property'}
{lable:'symbol-reference'}
{lable:'symbol-ruler'}
{lable:'symbol-snippet'}
{lable:'symbol-string'}
{lable:'symbol-struct'}
{lable:'symbol-structure'}
{lable:'symbol-text'}
{lable:'symbol-type-parameter'}
{lable:'symbol-unit'}
{lable:'symbol-value'}
{lable:'symbol-variable'}
{lable:'sync'}
{lable:'sync-ignored'}
{lable:'tag-add'}
{lable:'tag-remove'}
{lable:'tag'}
{lable:'target'}
{lable:'tasklist'}
{lable:'telescope'}
{lable:'terminal-bash'}
{lable:'terminal-cmd'}
{lable:'terminal-debian'}
{lable:'terminal-linux'}
{lable:'terminal-powershell'}
{lable:'terminal-tmux'}
{lable:'terminal-ubuntu'}
{lable:'terminal'}
{lable:'text-size'}
{lable:'three-bars'}
{lable:'thumbsdown'}
{lable:'thumbsdown-filled'}
{lable:'thumbsup'}
{lable:'thumbsup-filled'}
{lable:'tools'}
{lable:'trash'}
{lable:'trashcan'}
{lable:'triangle-down'}
{lable:'triangle-left'}
{lable:'triangle-right'}
{lable:'triangle-up'}
{lable:'twitter'}
{lable:'type-hierarchy'}
{lable:'type-hierarchy-sub'}
{lable:'type-hierarchy-super'}
{lable:'unfold'}
{lable:'ungroup-by-ref-type'}
{lable:'unlock'}
{lable:'unmute'}
{lable:'unverified'}
{lable:'variable'}
{lable:'verified-filled'}
{lable:'verified'}
{lable:'versions'}
{lable:'vm'}
{lable:'vm-active'}
{lable:'vm-connect'}
{lable:'vm-outline'}
{lable:'vm-running'}
{lable:'vr'}
{lable:'warning'}
{lable:'watch'}
{lable:'whitespace'}
{lable:'whole-word'}
{lable:'window'}
{lable:'word-wrap'}
{lable:'workspace-trusted'}
{lable:'workspace-unknown'}
{lable:'workspace-untrusted'}
{lable:'wrench'}
{lable:'wrench-subaction'}
{lable:'x'}
{lable:'zap'}
{lable:'zoom-in'}
{lable:'zoom-out'}
*/